--- # copying a file
- name: my test playbook
  hosts: webservers
  user: ansible
  become: true
  connection: ssh


  tasks:
    - name: copying a file
      copy:
        src: /home/ansible/index.html
        dest: /home/ansible
        owner: kiran
