--- # deleting a dir
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: deleting a directory
      file:
        path: /home/ansible/awsdirectory
        state: absent
