--- # my loops playbook
- hosts: webservers
  user: ansible
  become: true
  connection: ssh

  tasks: 
    - name: creating multiple user
      user: name='{{item}}' state=present
      with_items:
            - Raj
            - Xyz
            - Abc
            - Krish
            - Prabhas
            - Chiru
