---
- name: my test playbook
  hosts: all
  become: true

  tasks:
    - name: installing pkg
      yum:
        name: httpd
        state: absent

    - name: start service
      service:
        name: httpd
        state: stopped
