--- # my vars section
- hosts: all
  user: ansible
  become: yes
  connection: ssh
  

  vars:
    pkgname: httpd


  tasks:
    - name: install httpd on webservers
      action: yum name='{{pkgname}}' state=installed
